### ISSUE TITLE
ANS Time Error

### ISSUE THREAD

**Issue by mpars0ns** [mpars0ns/scansio-sonar-es#4]
Getting this error and having process hang
`Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "sonar_ssl.py", line 68, in process_scan_certs
    newcert = process_cert(certs['certs'])
  File "/home/mark/scansio-sonar-es/helpers/certparser.py", line 62, in process_cert
    notAfter = x509.get_notAfter()
  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 1220, in get_notAfter
    return self._get_boundary_time(_lib.X509_get_notAfter)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 1170, in _get_boundary_time
    return _get_asn1_time(which(self._x509))
  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 150, in _get_asn1_time
    _untested_error("ASN1_TIME_to_generalizedtime")
  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 49, in _untested_error
    raise RuntimeError("Unknown %s failure" % (where,))
RuntimeError: Unknown ASN1_TIME_to_generalizedtime failure`

**Comment by mpars0ns** [comment]
This is confirmed fixed. CLosing
